# Generated by Django 2.0.5 on 2019-09-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
